kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: demo-service-customer
  name: demo-service-customer 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-customer
  template:
    metadata:
      name: demo-service-customer
      labels:
        app: demo-service-customer
    spec:
      containers:
      - name: demo-service-customer
        image: repository:5000/demo-service-customer
        imagePullPolicy: Always
        env:
          - name: GIT_URL
            value: "http://demo-service-config:9000"


---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo-service-customer
  name: demo-service-customer
  namespace: default
spec:
  ports:
  - port: 9002 
    targetPort: 9002
  selector:
    app: demo-service-customer
