kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: demo-service-customer
  name: demo-service-customer 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-customer
  template:
    metadata:
      name: demo-service-customer
      labels:
        app: demo-service-customer
    spec:
      containers:
      - name: demo-service-customer
        image: 192.168.0.209:5000/demo-service-customer
        imagePullPolicy: Always
        env:
          - name: REGISTRY_URL
            value: "http://192.168.0.209:31001/eureka"


---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo-service-customer
  name: demo-service-customer
  namespace: default
spec:
  ports:
  - port: 9002 
    targetPort: 9002
  selector:
    app: demo-service-customer
